#This is a hackerrank code. I/P are generated by Hackerrank.com (Problem:Zipped by DOSHI)
"""
Print the averages of all students on separate lines.
The averages must be correct up to 1 decimal place.

eg I/P:
5 3 //Dimensions
89 90 78 93 80
90 91 85 88 86  
91 92 83 89 90.5

O/P:
90.0 
91.0 
82.0 
90.0 
85.5  

"""
dim=raw_input()
dim1=dim.split(" ")
c=int(dim1[0])
r=int(dim1[1])
s=['0' for i in range(r)]
l=['0' for i in range(r)]
for i in range(r):
    s[i]=raw_input()

for i in range(r):    
    l[i]=s[i].split(" ")

stud=[0 for i in range(c)]

j=0
k=0
while j!=c:
    for i in range(r):
        stud[j]=stud[j]+float(l[i][k])
    j+=1
    if k!=c:
        k+=1

for i in stud:
    print i/r
